=== pmfai25/fmk-schemas/etc/schemas/2015/06/01/UpdateAquireOrderResponse.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:medicinecard20150601="http://www.dkma.dk/medicinecard/xml.schema/2015/06/01" targetNamespace="http://www.dkma.dk/medicinecard/xml.schema/2015/06/01" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<include schemaLocation="PersonIdentifier.xsd"/>
	<include schemaLocation="MedicineCardVersion.xsd"/>
	<include schemaLocation="VersionMismatchWarning.xsd"/>
	<include schemaLocation="OrganisationIdentifier.xsd"/>
	<include schemaLocation="AquireOrderIdentifier.xsd"/>
	<include schemaLocation="AquireOrderVersion.xsd"/>

	<element name="UpdateAquireOrderResponse" type="medicinecard20150601:UpdateAquireOrderResponseType"/>

	<complexType name="UpdateAquireOrderResponseType">
		<sequence>
			<choice>
				<element name="PersonIdentifier" type="medicinecard20150601:PersonIdentifierType"/>
				<element name="OrganisationIdentifier" type="medicinecard20150601:OrganisationIdentifierType"/>
			</choice>
			<element name="MedicineCardVersion" type="medicinecard20150601:MedicineCardVersionType"/>
			<element name="VersionMismatchWarning" type="medicinecard20150601:VersionMismatchWarningType" minOccurs="0"/>
			<element name="AquireOrder" maxOccurs="unbounded">
				<complexType>
					<sequence>
						<element name="Identifier" type="medicinecard20150601:AquireOrderIdentifierType"/>
						<element name="Version" type="medicinecard20150601:AquireOrderVersionType"/>
						<element name="VersionMismatchWarning" type="medicinecard20150601:VersionMismatchWarningType" minOccurs="0"/>
					</sequence>
				</complexType>
			</element>
		</sequence>
	</complexType>
</schema>

=== pmfai25/fmk-schemas/etc/schemas/2014/06/01/UpdateAquireOrderResponse.xml
<?xml version="1.0" encoding="UTF-8"?>
<UpdateAquireOrderResponse xsi:schemaLocation="http://www.dkma.dk/medicinecard/xml.schema/2014/06/01 UpdateAquireOrderResponse.xsd" xmlns="http://www.dkma.dk/medicinecard/xml.schema/2014/06/01" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<PersonIdentifier source="CPR">1111111118</PersonIdentifier>
	<MedicineCardVersion>1341404078102001002</MedicineCardVersion>
	<VersionMismatchWarning/>
	<AquireOrder>
		<Identifier>1341404077656004002</Identifier>
		<Version>1341404078102001003</Version>
		<VersionMismatchWarning/>
	</AquireOrder>
</UpdateAquireOrderResponse>
